apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- ingress.yml

patchesStrategicMerge:
- deployment.yml

images:
- name: https://quay.io/pne_roberts/gatsby-simple-container
  newTag: ec8f34c
