name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Get the version
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build the tagged Docker image
        run: docker build . -t quay.io/pne_roberts/gatsby-simple-container:${{steps.vars.outputs.sha_short}}
      - name: Push the tagged Docker image
        run: docker push quay.io/pne_roberts/gatsby-simple-container:${{steps.vars.outputs.sha_short}}