name: Create preview environment

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: jzr1991/gatsby-simple-container-config
      - name: Create preview environment
        run: |
          cd $GITHUB_WORKSPACE
          ls -la
          mkdir gatsby-app/test-${{github.sha}}
          cp -R gatsby-app/dev/* gatsby-app/test-${{github.sha}}
          ls -la
          cd gatsby-app/test-${{github.sha}}
          ls -la
          pwd
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          kustomize edit set image quay.io/pne_roberts/gatsby-simple-container:${{github.sha}}
          kustomize edit set nameprefix {{github.head_ref}}
          cd ../
          echo "\n - test" >> kustomization.yaml
      - name: Commit new stuff
        run: |
          git config --global user.name 'Jack Roberts'
          git config --global user.email 'jzr1991@users.noreply.github.com'
          git commit -am "Automated report [skip ci]"
          git push