# name: Docker Image CI

# on:
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     container: k8s.gcr.io/kustomize/kustomize:v3.8.7
#     steps:
#       - uses: actions/checkout@v2
#       - name: Get the version
#         id: vars
#         run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
#       - name: Create preview environment
#         run: |
#           cp -R manifests/dev manifests/${{github.head_ref }
#           cd manifests/${{github.head_ref}}
#           kustomize edit set image quay.io/pne_roberts/gatsby-simple-container:${{steps.vars.outputs.sha_short}}
#           cd ../
#           echo '\n - test' >> manifests/kustomization.yaml
#           echo '\n - test' >> manifests/kustomization.yaml
#       - name: Commit new stuff
#         run: |
#           git config --global user.name 'Jack Roberts'
#           git config --global user.email 'jzr1991@users.noreply.github.com'
#           git commit -am "Automated report [skip ci]"
#           git push